twig:
    paths:
      '%kernel.project_dir%/templates': __main__
      # Your custom paths
      '%kernel.project_dir%/templates/default': default
      '%kernel.project_dir%/templates/admin': admin
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        siteName: 'Vulcano'