FrontOffice:
    resource: ../../src/Components/FrontOffice/Controller/
    type: annotation
    prefix: /

BackOffice:
    resource: ../../src/Components/BackOffice/Controller/
    type: annotation
    prefix: /admin